# Generated by Django 5.2.11 on 2026-04-21 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('patient_code', models.CharField(max_length=50, verbose_name='Код пациента (история болезни)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'db_table': 'patients',
                'ordering': ['-created_at'],
                'unique_together': {('doctor', 'patient_code')},
            },
        ),
        migrations.CreateModel(
            name='ExaminationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='Дата посещения')),
                ('complaint', models.TextField(blank=True, verbose_name='Жалобы')),
                ('anamnesis_morbi', models.TextField(blank=True, verbose_name='Анамнез заболевания')),
                ('anamnesis_vitae', models.TextField(blank=True, verbose_name='Анамнез жизни')),
                ('allergies', models.TextField(blank=True, verbose_name='Аллергологический анамнез')),
                ('face_symmetry', models.CharField(blank=True, choices=[('symmetric', 'Симметричное'), ('asymmetric', 'Асимметричное')], max_length=20, verbose_name='Конфигурация лица')),
                ('lymph_nodes', models.TextField(blank=True, verbose_name='Лимфатические узлы')),
                ('tmj_status', models.TextField(blank=True, verbose_name='Состояние ВНЧС')),
                ('mucosa_status', models.TextField(blank=True, verbose_name='Слизистая оболочка')),
                ('gum_status', models.TextField(blank=True, verbose_name='Дёсны / пародонт')),
                ('bite_type', models.CharField(blank=True, choices=[('orthognathic', 'Ортогнатический'), ('prognathic', 'Прогнатический'), ('deep', 'Глубокий'), ('open', 'Открытый'), ('cross', 'Перекрёстный'), ('other', 'Другой')], max_length=50, verbose_name='Прикус')),
                ('teeth_chart', models.JSONField(blank=True, default=dict, verbose_name='Зубная карта')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Диагноз')),
                ('treatment_plan', models.TextField(blank=True, verbose_name='План лечения')),
                ('treatment_done', models.TextField(blank=True, verbose_name='Проведённое лечение')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_cards', to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Карта осмотра',
                'verbose_name_plural': 'Карты осмотра',
                'db_table': 'examination_cards',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
    ]
