# Generated by Django 5.2.11 on 2026-04-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinationcard',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='examinationcard',
            name='anamnesis_morbi',
        ),
        migrations.RemoveField(
            model_name='examinationcard',
            name='anamnesis_vitae',
        ),
        migrations.RemoveField(
            model_name='examinationcard',
            name='bite_type',
        ),
        migrations.RemoveField(
            model_name='examinationcard',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='examinationcard',
            name='face_symmetry',
        ),
        migrations.RemoveField(
            model_name='examinationcard',
            name='gum_status',
        ),
        migrations.RemoveField(
            model_name='examinationcard',
            name='lymph_nodes',
        ),
        migrations.RemoveField(
            model_name='examinationcard',
            name='mucosa_status',
        ),
        migrations.RemoveField(
            model_name='examinationcard',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='examinationcard',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='examinationcard',
            name='tmj_status',
        ),
        migrations.RemoveField(
            model_name='examinationcard',
            name='treatment_done',
        ),
        migrations.RemoveField(
            model_name='examinationcard',
            name='treatment_plan',
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_code',
            field=models.CharField(max_length=50, verbose_name='Код пациента (из история болезни)'),
        ),
    ]
