# Generated by Django 5.2.11 on 2026-05-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_examinationcard_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinationcard',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='examinationcard',
            name='teeth_chart',
        ),
        migrations.AddField(
            model_name='examinationcard',
            name='diagnosis_text',
            field=models.TextField(blank=True, verbose_name='Заключение врача (редактируемый текст)'),
        ),
        migrations.AddField(
            model_name='examinationcard',
            name='objective',
            field=models.JSONField(blank=True, default=dict, verbose_name='Объективные данные (осмотр и диагностика)'),
        ),
        migrations.AddField(
            model_name='examinationcard',
            name='subjective',
            field=models.JSONField(blank=True, default=dict, verbose_name='Субъективные данные (жалобы и анамнез)'),
        ),
    ]
