# Generated by Django 5.2.11 on 2026-06-02 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_examinationcard_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationcard',
            name='tooth_count',
            field=models.PositiveSmallIntegerField(default=32, help_text='Фактическое число зубов (1–32).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)], verbose_name='Количество зубов у пациента'),
        ),
    ]
